caterwaul.module( 'vector' , (function(qs,qs1,qs2,qs3,qs4,qs5,qs6,qs7,qs8,qs9,qsa,qsb,qsc,qsd,qse,qsf,qsg,qsh,qsi,qsj,qsk,qsl,qsm,qsn,qso,qsp,qsq,qsr,qss,qst,qsu,qsv,qsw,qsx,qsy,qsz,qs10,qs11,qs12,qs13,qs14,qs15,qs16,qs17,qs18,qs19,qs1a) {var result= (function($) { (function() {var generator=function(base,composite) {;
return function(n,prefix) {;
return(function() {var compiled_base=base(n) ;
return rename($.merge( {} ,compiled_base,composite(compiled_base) ) ,prefix) } ) .call(this) } } ,rename=function(o,prefix) {;
return(function(xs) {var x,x0,xi,xl,xr;
var xr=new xs.constructor() ;
for(var x in xs)if(Object.prototype.hasOwnProperty.call(xs,x) )xr[ ( '' + (prefix|| "" ) + '' + (x) + '' ) ] =xs[x] ;
return xr} ) .call(this,o) } ,compile_function=function(xs,e) {;
return $.compile( (qs) .replace( {_formals:xs,_e:e} ) ) } ,base_v=function(n) {;
return(function() {var r=function(n,formals,wrap,fold,each) {;
return(function() {var body= (wrap) .replace( {x: (function(xs) {var x,x0,xi,xl,xr;
for(var x0=xs[0] ,xi=1,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,x0= ( (fold) .replace( {x:x0,y:x} ) ) ;
return x0} ) .call(this, (function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,xr.push( ( (each) .replace( {i: ( '' + (x) + '' ) } ) ) ) ;
return xr} ) .call(this, (function(i,u,s) {if( (u-i) *s<=0)return[] ;
for(var r= [] ,d=u-i;
d>0?i<u
:i>u;
i+=s)r.push(i) ;
return r} ) ( (0) , (n) , (1) ) ) ) } ) ;
return compile_function(formals,body) } ) .call(this) } ;
return{plus:r(n,qs1,qs2,qs3,qs4) ,times:r(n,qs5,qs6,qs7,qs8) ,minus:r(n,qs9,qsa,qsb,qsc) ,scale:r(n,qsd,qse,qsf,qsg) ,dot:r(n,qsh,qsi,qsj,qsk) ,norm:r(n,qsl,qsm,qsn,qso) ,min:r(n,qsp,qsq,qsr,qss) ,max:r(n,qst,qsu,qsv,qsw) ,macv:r(n,qsx,qsy,qsz,qs10) ,macs:r(n,qs11,qs12,qs13,qs14) } } ) .call(this) } ,composite_v=function(base) {;
return(function() {var ref_compile=function(functions,formals,body) {;
return(function() {var new_body= (body) .replace( (function(xs) {var x,x0,xi,xl,xr;
var xr=new xs.constructor() ;
for(var k in xs)if(Object.prototype.hasOwnProperty.call(xs,k) )x=xs[k] ,xr[k] = (new $.ref(x) ) ;
return xr} ) .call(this,functions) ) ;
return compile_function(formals,new_body) } ) .call(this) } ;
return{unit:ref_compile(base,qs15,qs16) ,proj:ref_compile(base,qs17,qs18) ,orth:ref_compile(base,qs19,qs1a) } } ) .call(this) } ;
return $.vector=generator(base_v,composite_v) } ) .call(this) } ) ;
result.caterwaul_expression_ref_table= {qs: ( "new caterwaul.syntax( \"(\" ,new caterwaul.syntax( \"function\" ,new caterwaul.syntax( \"(\" ,new caterwaul.syntax( \"_formals\" ) ) ,new caterwaul.syntax( \"{\" ,new caterwaul.syntax( \"return\" ,new caterwaul.syntax( \"_e\" ) ) ) ) )" ) ,qs1: ( "new caterwaul.syntax( \",\" ,new caterwaul.syntax( \"a\" ) ,new caterwaul.syntax( \"b\" ) )" ) ,qs2: ( "new caterwaul.syntax( \"[\" ,new caterwaul.syntax( \"x\" ) )" ) ,qs3: ( "new caterwaul.syntax( \",\" ,new caterwaul.syntax( \"x\" ) ,new caterwaul.syntax( \"y\" ) )" ) ,qs4: ( "new caterwaul.syntax( \"+\" ,new caterwaul.syntax( \"[]\" ,new caterwaul.syntax( \"a\" ) ,new caterwaul.syntax( \"i\" ) ) ,new caterwaul.syntax( \"[]\" ,new caterwaul.syntax( \"b\" ) ,new caterwaul.syntax( \"i\" ) ) )" ) ,qs5: ( "new caterwaul.syntax( \",\" ,new caterwaul.syntax( \"a\" ) ,new caterwaul.syntax( \"b\" ) )" ) ,qs6: ( "new caterwaul.syntax( \"[\" ,new caterwaul.syntax( \"x\" ) )" ) ,qs7: ( "new caterwaul.syntax( \",\" ,new caterwaul.syntax( \"x\" ) ,new caterwaul.syntax( \"y\" ) )" ) ,qs8: ( "new caterwaul.syntax( \"*\" ,new caterwaul.syntax( \"[]\" ,new caterwaul.syntax( \"a\" ) ,new caterwaul.syntax( \"i\" ) ) ,new caterwaul.syntax( \"[]\" ,new caterwaul.syntax( \"b\" ) ,new caterwaul.syntax( \"i\" ) ) )" ) ,qs9: ( "new caterwaul.syntax( \",\" ,new caterwaul.syntax( \"a\" ) ,new caterwaul.syntax( \"b\" ) )" ) ,qsa: ( "new caterwaul.syntax( \"[\" ,new caterwaul.syntax( \"x\" ) )" ) ,qsb: ( "new caterwaul.syntax( \",\" ,new caterwaul.syntax( \"x\" ) ,new caterwaul.syntax( \"y\" ) )" ) ,qsc: ( "new caterwaul.syntax( \"-\" ,new caterwaul.syntax( \"[]\" ,new caterwaul.syntax( \"a\" ) ,new caterwaul.syntax( \"i\" ) ) ,new caterwaul.syntax( \"[]\" ,new caterwaul.syntax( \"b\" ) ,new caterwaul.syntax( \"i\" ) ) )" ) ,qsd: ( "new caterwaul.syntax( \",\" ,new caterwaul.syntax( \"a\" ) ,new caterwaul.syntax( \"b\" ) )" ) ,qse: ( "new caterwaul.syntax( \"[\" ,new caterwaul.syntax( \"x\" ) )" ) ,qsf: ( "new caterwaul.syntax( \",\" ,new caterwaul.syntax( \"x\" ) ,new caterwaul.syntax( \"y\" ) )" ) ,qsg: ( "new caterwaul.syntax( \"*\" ,new caterwaul.syntax( \"[]\" ,new caterwaul.syntax( \"a\" ) ,new caterwaul.syntax( \"i\" ) ) ,new caterwaul.syntax( \"b\" ) )" ) ,qsh: ( "new caterwaul.syntax( \",\" ,new caterwaul.syntax( \"a\" ) ,new caterwaul.syntax( \"b\" ) )" ) ,qsi: ( "new caterwaul.syntax( \"x\" )" ) ,qsj: ( "new caterwaul.syntax( \"+\" ,new caterwaul.syntax( \"x\" ) ,new caterwaul.syntax( \"y\" ) )" ) ,qsk: ( "new caterwaul.syntax( \"*\" ,new caterwaul.syntax( \"[]\" ,new caterwaul.syntax( \"a\" ) ,new caterwaul.syntax( \"i\" ) ) ,new caterwaul.syntax( \"[]\" ,new caterwaul.syntax( \"b\" ) ,new caterwaul.syntax( \"i\" ) ) )" ) ,qsl: ( "new caterwaul.syntax( \"a\" )" ) ,qsm: ( "new caterwaul.syntax( \"()\" ,new caterwaul.syntax( \".\" ,new caterwaul.syntax( \"Math\" ) ,new caterwaul.syntax( \"sqrt\" ) ) ,new caterwaul.syntax( \"x\" ) )" ) ,qsn: ( "new caterwaul.syntax( \"+\" ,new caterwaul.syntax( \"x\" ) ,new caterwaul.syntax( \"y\" ) )" ) ,qso: ( "new caterwaul.syntax( \"*\" ,new caterwaul.syntax( \"[]\" ,new caterwaul.syntax( \"a\" ) ,new caterwaul.syntax( \"i\" ) ) ,new caterwaul.syntax( \"[]\" ,new caterwaul.syntax( \"a\" ) ,new caterwaul.syntax( \"i\" ) ) )" ) ,qsp: ( "new caterwaul.syntax( \",\" ,new caterwaul.syntax( \"a\" ) ,new caterwaul.syntax( \"b\" ) )" ) ,qsq: ( "new caterwaul.syntax( \"[\" ,new caterwaul.syntax( \"x\" ) )" ) ,qsr: ( "new caterwaul.syntax( \",\" ,new caterwaul.syntax( \"x\" ) ,new caterwaul.syntax( \"y\" ) )" ) ,qss: ( "new caterwaul.syntax( \"()\" ,new caterwaul.syntax( \".\" ,new caterwaul.syntax( \"Math\" ) ,new caterwaul.syntax( \"min\" ) ) ,new caterwaul.syntax( \",\" ,new caterwaul.syntax( \"[]\" ,new caterwaul.syntax( \"a\" ) ,new caterwaul.syntax( \"i\" ) ) ,new caterwaul.syntax( \"[]\" ,new caterwaul.syntax( \"b\" ) ,new caterwaul.syntax( \"i\" ) ) ) )" ) ,qst: ( "new caterwaul.syntax( \",\" ,new caterwaul.syntax( \"a\" ) ,new caterwaul.syntax( \"b\" ) )" ) ,qsu: ( "new caterwaul.syntax( \"[\" ,new caterwaul.syntax( \"x\" ) )" ) ,qsv: ( "new caterwaul.syntax( \",\" ,new caterwaul.syntax( \"x\" ) ,new caterwaul.syntax( \"y\" ) )" ) ,qsw: ( "new caterwaul.syntax( \"()\" ,new caterwaul.syntax( \".\" ,new caterwaul.syntax( \"Math\" ) ,new caterwaul.syntax( \"max\" ) ) ,new caterwaul.syntax( \",\" ,new caterwaul.syntax( \"[]\" ,new caterwaul.syntax( \"a\" ) ,new caterwaul.syntax( \"i\" ) ) ,new caterwaul.syntax( \"[]\" ,new caterwaul.syntax( \"b\" ) ,new caterwaul.syntax( \"i\" ) ) ) )" ) ,qsx: ( "new caterwaul.syntax( \",\" ,new caterwaul.syntax( \",\" ,new caterwaul.syntax( \"a\" ) ,new caterwaul.syntax( \"b\" ) ) ,new caterwaul.syntax( \"c\" ) )" ) ,qsy: ( "new caterwaul.syntax( \"[\" ,new caterwaul.syntax( \"x\" ) )" ) ,qsz: ( "new caterwaul.syntax( \"[\" ,new caterwaul.syntax( \",\" ,new caterwaul.syntax( \"x\" ) ,new caterwaul.syntax( \"y\" ) ) )" ) ,qs10: ( "new caterwaul.syntax( \"+\" ,new caterwaul.syntax( \"[]\" ,new caterwaul.syntax( \"a\" ) ,new caterwaul.syntax( \"i\" ) ) ,new caterwaul.syntax( \"*\" ,new caterwaul.syntax( \"[]\" ,new caterwaul.syntax( \"b\" ) ,new caterwaul.syntax( \"i\" ) ) ,new caterwaul.syntax( \"[]\" ,new caterwaul.syntax( \"c\" ) ,new caterwaul.syntax( \"i\" ) ) ) )" ) ,qs11: ( "new caterwaul.syntax( \",\" ,new caterwaul.syntax( \",\" ,new caterwaul.syntax( \"a\" ) ,new caterwaul.syntax( \"b\" ) ) ,new caterwaul.syntax( \"c\" ) )" ) ,qs12: ( "new caterwaul.syntax( \"[\" ,new caterwaul.syntax( \"x\" ) )" ) ,qs13: ( "new caterwaul.syntax( \"[\" ,new caterwaul.syntax( \",\" ,new caterwaul.syntax( \"x\" ) ,new caterwaul.syntax( \"y\" ) ) )" ) ,qs14: ( "new caterwaul.syntax( \"+\" ,new caterwaul.syntax( \"[]\" ,new caterwaul.syntax( \"a\" ) ,new caterwaul.syntax( \"i\" ) ) ,new caterwaul.syntax( \"*\" ,new caterwaul.syntax( \"b\" ) ,new caterwaul.syntax( \"[]\" ,new caterwaul.syntax( \"c\" ) ,new caterwaul.syntax( \"i\" ) ) ) )" ) ,qs15: ( "new caterwaul.syntax( \"a\" )" ) ,qs16: ( "new caterwaul.syntax( \"()\" ,new caterwaul.syntax( \"scale\" ) ,new caterwaul.syntax( \",\" ,new caterwaul.syntax( \"a\" ) ,new caterwaul.syntax( \"/\" ,new caterwaul.syntax( \"1.0\" ) ,new caterwaul.syntax( \"()\" ,new caterwaul.syntax( \"norm\" ) ,new caterwaul.syntax( \"a\" ) ) ) ) )" ) ,qs17: ( "new caterwaul.syntax( \",\" ,new caterwaul.syntax( \"a\" ) ,new caterwaul.syntax( \"b\" ) )" ) ,qs18: ( "new caterwaul.syntax( \"()\" ,new caterwaul.syntax( \"scale\" ) ,new caterwaul.syntax( \",\" ,new caterwaul.syntax( \"b\" ) ,new caterwaul.syntax( \"/\" ,new caterwaul.syntax( \"()\" ,new caterwaul.syntax( \"dot\" ) ,new caterwaul.syntax( \",\" ,new caterwaul.syntax( \"a\" ) ,new caterwaul.syntax( \"b\" ) ) ) ,new caterwaul.syntax( \"()\" ,new caterwaul.syntax( \"dot\" ) ,new caterwaul.syntax( \",\" ,new caterwaul.syntax( \"b\" ) ,new caterwaul.syntax( \"b\" ) ) ) ) ) )" ) ,qs19: ( "new caterwaul.syntax( \",\" ,new caterwaul.syntax( \"a\" ) ,new caterwaul.syntax( \"b\" ) )" ) ,qs1a: ( "new caterwaul.syntax( \"()\" ,new caterwaul.syntax( \"minus\" ) ,new caterwaul.syntax( \",\" ,new caterwaul.syntax( \"a\" ) ,new caterwaul.syntax( \"()\" ,new caterwaul.syntax( \"scale\" ) ,new caterwaul.syntax( \",\" ,new caterwaul.syntax( \"b\" ) ,new caterwaul.syntax( \"/\" ,new caterwaul.syntax( \"()\" ,new caterwaul.syntax( \"dot\" ) ,new caterwaul.syntax( \",\" ,new caterwaul.syntax( \"a\" ) ,new caterwaul.syntax( \"b\" ) ) ) ,new caterwaul.syntax( \"()\" ,new caterwaul.syntax( \"dot\" ) ,new caterwaul.syntax( \",\" ,new caterwaul.syntax( \"b\" ) ,new caterwaul.syntax( \"b\" ) ) ) ) ) ) ) )" ) } ;
return(result) } ) .call(this,new caterwaul.syntax( "(" ,new caterwaul.syntax( "function" ,new caterwaul.syntax( "(" ,new caterwaul.syntax( "_formals" ) ) ,new caterwaul.syntax( "{" ,new caterwaul.syntax( "return" ,new caterwaul.syntax( "_e" ) ) ) ) ) ,new caterwaul.syntax( "," ,new caterwaul.syntax( "a" ) ,new caterwaul.syntax( "b" ) ) ,new caterwaul.syntax( "[" ,new caterwaul.syntax( "x" ) ) ,new caterwaul.syntax( "," ,new caterwaul.syntax( "x" ) ,new caterwaul.syntax( "y" ) ) ,new caterwaul.syntax( "+" ,new caterwaul.syntax( "[]" ,new caterwaul.syntax( "a" ) ,new caterwaul.syntax( "i" ) ) ,new caterwaul.syntax( "[]" ,new caterwaul.syntax( "b" ) ,new caterwaul.syntax( "i" ) ) ) ,new caterwaul.syntax( "," ,new caterwaul.syntax( "a" ) ,new caterwaul.syntax( "b" ) ) ,new caterwaul.syntax( "[" ,new caterwaul.syntax( "x" ) ) ,new caterwaul.syntax( "," ,new caterwaul.syntax( "x" ) ,new caterwaul.syntax( "y" ) ) ,new caterwaul.syntax( "*" ,new caterwaul.syntax( "[]" ,new caterwaul.syntax( "a" ) ,new caterwaul.syntax( "i" ) ) ,new caterwaul.syntax( "[]" ,new caterwaul.syntax( "b" ) ,new caterwaul.syntax( "i" ) ) ) ,new caterwaul.syntax( "," ,new caterwaul.syntax( "a" ) ,new caterwaul.syntax( "b" ) ) ,new caterwaul.syntax( "[" ,new caterwaul.syntax( "x" ) ) ,new caterwaul.syntax( "," ,new caterwaul.syntax( "x" ) ,new caterwaul.syntax( "y" ) ) ,new caterwaul.syntax( "-" ,new caterwaul.syntax( "[]" ,new caterwaul.syntax( "a" ) ,new caterwaul.syntax( "i" ) ) ,new caterwaul.syntax( "[]" ,new caterwaul.syntax( "b" ) ,new caterwaul.syntax( "i" ) ) ) ,new caterwaul.syntax( "," ,new caterwaul.syntax( "a" ) ,new caterwaul.syntax( "b" ) ) ,new caterwaul.syntax( "[" ,new caterwaul.syntax( "x" ) ) ,new caterwaul.syntax( "," ,new caterwaul.syntax( "x" ) ,new caterwaul.syntax( "y" ) ) ,new caterwaul.syntax( "*" ,new caterwaul.syntax( "[]" ,new caterwaul.syntax( "a" ) ,new caterwaul.syntax( "i" ) ) ,new caterwaul.syntax( "b" ) ) ,new caterwaul.syntax( "," ,new caterwaul.syntax( "a" ) ,new caterwaul.syntax( "b" ) ) ,new caterwaul.syntax( "x" ) ,new caterwaul.syntax( "+" ,new caterwaul.syntax( "x" ) ,new caterwaul.syntax( "y" ) ) ,new caterwaul.syntax( "*" ,new caterwaul.syntax( "[]" ,new caterwaul.syntax( "a" ) ,new caterwaul.syntax( "i" ) ) ,new caterwaul.syntax( "[]" ,new caterwaul.syntax( "b" ) ,new caterwaul.syntax( "i" ) ) ) ,new caterwaul.syntax( "a" ) ,new caterwaul.syntax( "()" ,new caterwaul.syntax( "." ,new caterwaul.syntax( "Math" ) ,new caterwaul.syntax( "sqrt" ) ) ,new caterwaul.syntax( "x" ) ) ,new caterwaul.syntax( "+" ,new caterwaul.syntax( "x" ) ,new caterwaul.syntax( "y" ) ) ,new caterwaul.syntax( "*" ,new caterwaul.syntax( "[]" ,new caterwaul.syntax( "a" ) ,new caterwaul.syntax( "i" ) ) ,new caterwaul.syntax( "[]" ,new caterwaul.syntax( "a" ) ,new caterwaul.syntax( "i" ) ) ) ,new caterwaul.syntax( "," ,new caterwaul.syntax( "a" ) ,new caterwaul.syntax( "b" ) ) ,new caterwaul.syntax( "[" ,new caterwaul.syntax( "x" ) ) ,new caterwaul.syntax( "," ,new caterwaul.syntax( "x" ) ,new caterwaul.syntax( "y" ) ) ,new caterwaul.syntax( "()" ,new caterwaul.syntax( "." ,new caterwaul.syntax( "Math" ) ,new caterwaul.syntax( "min" ) ) ,new caterwaul.syntax( "," ,new caterwaul.syntax( "[]" ,new caterwaul.syntax( "a" ) ,new caterwaul.syntax( "i" ) ) ,new caterwaul.syntax( "[]" ,new caterwaul.syntax( "b" ) ,new caterwaul.syntax( "i" ) ) ) ) ,new caterwaul.syntax( "," ,new caterwaul.syntax( "a" ) ,new caterwaul.syntax( "b" ) ) ,new caterwaul.syntax( "[" ,new caterwaul.syntax( "x" ) ) ,new caterwaul.syntax( "," ,new caterwaul.syntax( "x" ) ,new caterwaul.syntax( "y" ) ) ,new caterwaul.syntax( "()" ,new caterwaul.syntax( "." ,new caterwaul.syntax( "Math" ) ,new caterwaul.syntax( "max" ) ) ,new caterwaul.syntax( "," ,new caterwaul.syntax( "[]" ,new caterwaul.syntax( "a" ) ,new caterwaul.syntax( "i" ) ) ,new caterwaul.syntax( "[]" ,new caterwaul.syntax( "b" ) ,new caterwaul.syntax( "i" ) ) ) ) ,new caterwaul.syntax( "," ,new caterwaul.syntax( "," ,new caterwaul.syntax( "a" ) ,new caterwaul.syntax( "b" ) ) ,new caterwaul.syntax( "c" ) ) ,new caterwaul.syntax( "[" ,new caterwaul.syntax( "x" ) ) ,new caterwaul.syntax( "[" ,new caterwaul.syntax( "," ,new caterwaul.syntax( "x" ) ,new caterwaul.syntax( "y" ) ) ) ,new caterwaul.syntax( "+" ,new caterwaul.syntax( "[]" ,new caterwaul.syntax( "a" ) ,new caterwaul.syntax( "i" ) ) ,new caterwaul.syntax( "*" ,new caterwaul.syntax( "[]" ,new caterwaul.syntax( "b" ) ,new caterwaul.syntax( "i" ) ) ,new caterwaul.syntax( "[]" ,new caterwaul.syntax( "c" ) ,new caterwaul.syntax( "i" ) ) ) ) ,new caterwaul.syntax( "," ,new caterwaul.syntax( "," ,new caterwaul.syntax( "a" ) ,new caterwaul.syntax( "b" ) ) ,new caterwaul.syntax( "c" ) ) ,new caterwaul.syntax( "[" ,new caterwaul.syntax( "x" ) ) ,new caterwaul.syntax( "[" ,new caterwaul.syntax( "," ,new caterwaul.syntax( "x" ) ,new caterwaul.syntax( "y" ) ) ) ,new caterwaul.syntax( "+" ,new caterwaul.syntax( "[]" ,new caterwaul.syntax( "a" ) ,new caterwaul.syntax( "i" ) ) ,new caterwaul.syntax( "*" ,new caterwaul.syntax( "b" ) ,new caterwaul.syntax( "[]" ,new caterwaul.syntax( "c" ) ,new caterwaul.syntax( "i" ) ) ) ) ,new caterwaul.syntax( "a" ) ,new caterwaul.syntax( "()" ,new caterwaul.syntax( "scale" ) ,new caterwaul.syntax( "," ,new caterwaul.syntax( "a" ) ,new caterwaul.syntax( "/" ,new caterwaul.syntax( "1.0" ) ,new caterwaul.syntax( "()" ,new caterwaul.syntax( "norm" ) ,new caterwaul.syntax( "a" ) ) ) ) ) ,new caterwaul.syntax( "," ,new caterwaul.syntax( "a" ) ,new caterwaul.syntax( "b" ) ) ,new caterwaul.syntax( "()" ,new caterwaul.syntax( "scale" ) ,new caterwaul.syntax( "," ,new caterwaul.syntax( "b" ) ,new caterwaul.syntax( "/" ,new caterwaul.syntax( "()" ,new caterwaul.syntax( "dot" ) ,new caterwaul.syntax( "," ,new caterwaul.syntax( "a" ) ,new caterwaul.syntax( "b" ) ) ) ,new caterwaul.syntax( "()" ,new caterwaul.syntax( "dot" ) ,new caterwaul.syntax( "," ,new caterwaul.syntax( "b" ) ,new caterwaul.syntax( "b" ) ) ) ) ) ) ,new caterwaul.syntax( "," ,new caterwaul.syntax( "a" ) ,new caterwaul.syntax( "b" ) ) ,new caterwaul.syntax( "()" ,new caterwaul.syntax( "minus" ) ,new caterwaul.syntax( "," ,new caterwaul.syntax( "a" ) ,new caterwaul.syntax( "()" ,new caterwaul.syntax( "scale" ) ,new caterwaul.syntax( "," ,new caterwaul.syntax( "b" ) ,new caterwaul.syntax( "/" ,new caterwaul.syntax( "()" ,new caterwaul.syntax( "dot" ) ,new caterwaul.syntax( "," ,new caterwaul.syntax( "a" ) ,new caterwaul.syntax( "b" ) ) ) ,new caterwaul.syntax( "()" ,new caterwaul.syntax( "dot" ) ,new caterwaul.syntax( "," ,new caterwaul.syntax( "b" ) ,new caterwaul.syntax( "b" ) ) ) ) ) ) ) ) ) ) ;

caterwaul.module( 'splunge' , (function(e1) {var result= (function($) {$.splunge= (function() {var(function() {var vplus=e1.vplus,vtimes=e1.vtimes,vminus=e1.vminus,vscale=e1.vscale,vdot=e1.vdot,vnorm=e1.vnorm,vmin=e1.vmin,vmax=e1.vmax,vmacv=e1.vmacv,vmacs=e1.vmacs,vunit=e1.vunit,vproj=e1.vproj,vorth=e1.vorth;
return atan_scale=2/Math.PI,scaled_atan=function(x) {;
return Math.atan(x) *atan_scale} ,clip=function(x) {;
return Math.min(Math.max(x, -1) ,1) } ,id=function(x) {;
return x} ,scaled_tan=function(x) {;
return Math.tan(clip(x/atan_scale) ) } ,componentwise=function(f1,f2) {;
return function(v) {;
return[f1(v[0] ) ,f2(v[1] ) ] } } ,x_tangent= {transform:componentwise(scaled_tan,id) ,inverse:function() {;
return x_arctangent} } ,x_arctangent= {transform:componentwise(scaled_atan,id) ,inverse:function() {;
return x_tangent} } ,y_tangent= {transform:componentwise(id,scaled_tan) ,inverse:function() {;
return y_arctangent} } ,y_arctangent= {transform:componentwise(id,scaled_atan) ,inverse:function() {;
return y_tangent} } ,inverse_polar= {transform:function(v) {var d=vnorm(v) ;
var t=Math.atan2(v[0] ,v[1] ) ;
return[d,t] } ,inverse:function() {;
return polar} } ,polar= {transform:function(v) {var d=v[0] ;
var t=v[1] ;
return[d*Math.cos(t) ,d*Math.sin(t) ] } ,inverse:function() {;
return inverse_polar} } ,composite=function() {var ts=arguments;
return{transform:function(v) {;
return(function(xs) {var x,x0,xi,xl,xr;
for(var x0= (v) ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,x0= (x(x0) ) ;
return x0} ) .call(this,ts) } ,inverse:function() {;
return composite.apply(this, (function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,xr.push( (ts[xl-xi-1] .inverse() ) ) ;
return xr} ) .call(this,ts) ) } } } ,box=function(v,dv) {;
return new box_ctor(v,dv) } ,translate=function(v) {;
return new box_ctor(v, [1,1] ) } ,bound_everything=box( [ -1/0, -1/0] , [1/0,1/0] ) ,rectangle=function(data,v,dv) {var b=box(v,dv) ;
return(b.data=data,b) } ,scale=function(v) {;
return new box_ctor( [0,0] ,v) } ,bound_nothing=box( [0,0] , [0,0] ) ,box_ctor= (function(it) {return $.merge(it.prototype, {area:function() {;
return this.dv[0] *this.dv[1] } ,plus:function(b) {;
return box(vplus(this.v,b.v) ,vplus(this.dv,b.dv) ) } ,interpolate:function(b,x) {;
return(this.scale(1-x) ) .plus(b.scale(x) ) } ,scale:function(x) {;
return box(vscale(this.v,x) ,vscale(this.dv,x) ) } ,transform:function(v) {;
return vplus(this.v,vtimes(v,this.dv) ) } ,inverse:function() {;
return box(vscale(this.v, -1) , [1/this.dv[0] ,1/this.dv[1] ] ) } ,times:function(v) {;
return box(this.v,vtimes(v,this.dv) ) } ,bound:function() {;
return this} ,intersect:function(b) {;
return(this) .map_corners(function(_) {return(b) .intern(_) } ) } ,union:function(b) {;
return(function() {var c1=vmin(this.v,b.v) ,c2=vmax(vplus(this.v,this.dv) ,vplus(b.v,b.dv) ) ;
return box(c1,vminus(c2,c1) ) } ) .call(this) } ,transform_with:function(t) {;
return(this) .map_corners(function(_) {return(t) .transform(_) } ) } ,intern:function(v) {;
return vmin(vmax(v,this.v) ,vplus(this.v,this.dv) ) } ,contains:function(v) {;
return v[0] >=this.v[0] &&v[1] >=this.v[1] &&v[0] <=this.v[0] +this.dv[0] &&v[1] <=this.v[1] +this.dv[1] } ,map_corners:function(f) {;
return(function() {var c1=f(this.v) ,c2=f(vplus(this.v,this.dv) ) ;
return rectangle(this.data,c1,vminus(c2,c1) ) } ) .call(this) } } ) ,it} ) .call(this, ( (function(v,dv) {return this.v=v,this.dv=dv} ) ) ) ,cons=function(first,rest_fn) {;
return new cons_ctor(first,rest_fn) } ,cons_from_array=function(xs) {;
return(function(xs) {var x,x0,xi,xl,xr;
for(var x0= (null) ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,x0= (cons(x,k(x0) ) ) ;
return x0} ) .call(this,xs) } ,cons_to_array=function(c) {;
return c.reduce( [] , (function(x,rest) {return[x] .concat(rest() ) } ) ) } ,cons_ctor= (function(it) {return $.merge(it.prototype, {reduce:function(x,f) {var r=this.rest;
return f(this.first,r?function(_) {return r.reduce(x,f) } 
:x) } ,transform_with:function(t) {;
return map(function(_) {return _.transform_with(t) } ,this) } ,bound:function() {;
return bound_everything} } ) ,it} ) .call(this, ( (function(first,rest_fn) {return this.first=first,this.rest=rest_fn} ) ) ) ,k=function(x) {;
return function() {;
return x} } ,map=function(f,xs) {;
return xs.reduce(k(null) , (function(x,rest) {return cons(f(x) ,rest) } ) ) } ,append=function(xs,ys_f) {;
return xs===null?ys_f() 
:xs.reduce(ys_f,cons) } ,filter=function(f,xs) {;
return xs.reduce(k(null) , (function(x,rest) {return f(x) ?cons(x,rest) 
:rest() } ) ) } ,each=function(f,xs) {;
return xs.reduce(k(xs) , (function(x,rest) {return f(x) ,rest() } ) ) } ,take_while=function(f,xs) {;
return xs.reduce(k(null) , (function(x,rest) {return f(x) ?cons(x,rest) 
:null} ) ) } ,descend_while=function(f,xs) {;
return xs.reduce?xs.reduce(k(null) , (function(x,rest) {return take_while(f,append(descend_while(f,k(x) ) ,function(_) {return descend_while(f,rest() ) } ) ) } ) ) 
:x} ,bounded=function(s,box) {;
return{bound:function() {;
return box} ,reduce:function(x,f) {;
return f(s,x) } } } ,x_shadow=function(s,bound) {;
return bounded(s, (bound) .times( [1/0,1] ) ) } ,x_stack=function(xs) {;
return x_shadow(xs,xs.first.bound() ) } ,y_shadow=function(s,bound) {;
return bounded(s, (bound) .times( [1,1/0] ) ) } ,y_stack=function(xs) {;
return y_shadow(xs,xs.first.bound() ) } ,rectangle_path=function(b,c) {;
return c.rect(b.v[0] ,b.v[1] ,b.v[0] +b.dv[0] ,b.v[1] +b.dv[1] ) } ,arc_path=function(b,c) {;
return( ( ( ( (c.save() ,c.rotate(b.v[1] ) ) ,c.arc(0,0,b.v[0] ,0,b.dv[1] ) ) ,c.arc(0,0,b.v[0] +b.dv[0] ,b.dv[1] ,0,true) ) ,c.lineTo(b.v[0] ,0) ) ,c.restore() ) } ,arc_bound=function(b) {var p= (b) .transform_with(inverse_polar) ;
var cp1= (polar) .transform( [p.v[0] ,p.v[1] +p.dv[1] ] ) ;
var cp2= (polar) .transform( [p.v[0] +p.dv[0] ,p.v[1] ] ) ;
return(b) .union(box(cp1,cp2) ) } ,cosine_tween=function(x) {;
return Math.cos(x*Math.PI) * -0.5+0.5} ,viewport=function(data,zoom,view) {;
return{transformed_data:function() {;
return( (data) .transform_with(zoom) ) .transform_with(view) } ,with_zoom:function(z) {;
return viewport(data,z,view) } ,animate:function(to,duration,tween) {;
return animation(this,to,duration||400,tween||cosine_tween) } ,with_data:function(d) {;
return viewport(d,zoom,view) } ,find:function(v) {;
return descend_while(function(_) {return _.bound() .contains(v) } ) .first} ,zoom:function() {;
return zoom} ,view:function() {;
return view} ,data:function() {;
return data} ,interpolate:function(v,x) {;
return(this) .with_zoom(zoom.interpolate(v.zoom() ,x) ) } } } ,animation=function(v1,v2,duration,tween) {;
return{start: +new Date,viewport:function() {;
return v1.interpolate(v2,this.factor() ) } ,is_complete:function() {;
return+new Date-start>duration} ,factor:function() {var t= +new Date;
return Math.min(1,tween( (t-start) /duration) ) } } } ,drag_events=function(canvas) {;
return(function() {var last_x=0,last_y=0,dragging=false,last_selected=null,$doc=jQuery(document) ,self=jQuery(canvas) ,record=function(x,y) {;
return(last_x=x,last_y=y) } ,start_dragging=function(e) {;
return(record(e.pageX,e.pageY) , ( ($doc) .mousemove(drag) ) .mouseup(stop_dragging) ) } ,stop_dragging=function(e) {;
return $doc.unbind( 'mousemove' ,drag) .unbind( 'mouseup' ,stop_dragging) } ,drag=function(e) {;
return(self.trigger( 'drag_delta' ,$.merge( {} ,e, {dx:e.pageX-last_x,dy:e.pageY-last_y} ) ) ,record(e.pageX,e.pageY) ) } ;
return( !self.data( 'splunge_drag_delta_installed' ) &&self.mousedown(start_dragging) .data( 'splunge_drag_delta_installed' ,true) ,self) } ) .call(this) } ,default_interaction=function(canvas,v) {;
return(function() {var x_scale=function(v) {;
return v.transform() .dx} ,pan_or_scale=function(e) {;
return e.shiftKey?scale(e) 
:pan(e) } ,y_scale=function(v) {;
return v.transform() .dy} ,scale=function(e) {;
return v.transform(plus(base(v.transform() ) ,times(d(v.transform() ) , {x:e.dx,y:e.dy} ) ) ) } ;
return drag_events(canvas) .on( 'drag_delta' ,pan_or_scale) } ) .call(this) } } ) .call(this) ;
return{ (function() {var vplus=e1.vplus,vtimes=e1.vtimes,vminus=e1.vminus,vscale=e1.vscale,vdot=e1.vdot,vnorm=e1.vnorm,vmin=e1.vmin,vmax=e1.vmax,vmacv=e1.vmacv,vmacs=e1.vmacs,vunit=e1.vunit,vproj=e1.vproj,vorth=e1.vorth;
return atan_scale=2/Math.PI,scaled_atan=function(x) {;
return Math.atan(x) *atan_scale} ,clip=function(x) {;
return Math.min(Math.max(x, -1) ,1) } ,id=function(x) {;
return x} ,scaled_tan=function(x) {;
return Math.tan(clip(x/atan_scale) ) } ,componentwise=function(f1,f2) {;
return function(v) {;
return[f1(v[0] ) ,f2(v[1] ) ] } } ,x_tangent= {transform:componentwise(scaled_tan,id) ,inverse:function() {;
return x_arctangent} } ,x_arctangent= {transform:componentwise(scaled_atan,id) ,inverse:function() {;
return x_tangent} } ,y_tangent= {transform:componentwise(id,scaled_tan) ,inverse:function() {;
return y_arctangent} } ,y_arctangent= {transform:componentwise(id,scaled_atan) ,inverse:function() {;
return y_tangent} } ,inverse_polar= {transform:function(v) {var d=vnorm(v) ;
var t=Math.atan2(v[0] ,v[1] ) ;
return[d,t] } ,inverse:function() {;
return polar} } ,polar= {transform:function(v) {var d=v[0] ;
var t=v[1] ;
return[d*Math.cos(t) ,d*Math.sin(t) ] } ,inverse:function() {;
return inverse_polar} } ,composite=function() {var ts=arguments;
return{transform:function(v) {;
return(function(xs) {var x,x0,xi,xl,xr;
for(var x0= (v) ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,x0= (x(x0) ) ;
return x0} ) .call(this,ts) } ,inverse:function() {;
return composite.apply(this, (function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,xr.push( (ts[xl-xi-1] .inverse() ) ) ;
return xr} ) .call(this,ts) ) } } } ,box=function(v,dv) {;
return new box_ctor(v,dv) } ,translate=function(v) {;
return new box_ctor(v, [1,1] ) } ,bound_everything=box( [ -1/0, -1/0] , [1/0,1/0] ) ,rectangle=function(data,v,dv) {var b=box(v,dv) ;
return(b.data=data,b) } ,scale=function(v) {;
return new box_ctor( [0,0] ,v) } ,bound_nothing=box( [0,0] , [0,0] ) ,box_ctor= (function(it) {return $.merge(it.prototype, {area:function() {;
return this.dv[0] *this.dv[1] } ,plus:function(b) {;
return box(vplus(this.v,b.v) ,vplus(this.dv,b.dv) ) } ,interpolate:function(b,x) {;
return(this.scale(1-x) ) .plus(b.scale(x) ) } ,scale:function(x) {;
return box(vscale(this.v,x) ,vscale(this.dv,x) ) } ,transform:function(v) {;
return vplus(this.v,vtimes(v,this.dv) ) } ,inverse:function() {;
return box(vscale(this.v, -1) , [1/this.dv[0] ,1/this.dv[1] ] ) } ,times:function(v) {;
return box(this.v,vtimes(v,this.dv) ) } ,bound:function() {;
return this} ,intersect:function(b) {;
return(this) .map_corners(function(_) {return(b) .intern(_) } ) } ,union:function(b) {;
return(function() {var c1=vmin(this.v,b.v) ,c2=vmax(vplus(this.v,this.dv) ,vplus(b.v,b.dv) ) ;
return box(c1,vminus(c2,c1) ) } ) .call(this) } ,transform_with:function(t) {;
return(this) .map_corners(function(_) {return(t) .transform(_) } ) } ,intern:function(v) {;
return vmin(vmax(v,this.v) ,vplus(this.v,this.dv) ) } ,contains:function(v) {;
return v[0] >=this.v[0] &&v[1] >=this.v[1] &&v[0] <=this.v[0] +this.dv[0] &&v[1] <=this.v[1] +this.dv[1] } ,map_corners:function(f) {;
return(function() {var c1=f(this.v) ,c2=f(vplus(this.v,this.dv) ) ;
return rectangle(this.data,c1,vminus(c2,c1) ) } ) .call(this) } } ) ,it} ) .call(this, ( (function(v,dv) {return this.v=v,this.dv=dv} ) ) ) ,cons=function(first,rest_fn) {;
return new cons_ctor(first,rest_fn) } ,cons_from_array=function(xs) {;
return(function(xs) {var x,x0,xi,xl,xr;
for(var x0= (null) ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,x0= (cons(x,k(x0) ) ) ;
return x0} ) .call(this,xs) } ,cons_to_array=function(c) {;
return c.reduce( [] , (function(x,rest) {return[x] .concat(rest() ) } ) ) } ,cons_ctor= (function(it) {return $.merge(it.prototype, {reduce:function(x,f) {var r=this.rest;
return f(this.first,r?function(_) {return r.reduce(x,f) } 
:x) } ,transform_with:function(t) {;
return map(function(_) {return _.transform_with(t) } ,this) } ,bound:function() {;
return bound_everything} } ) ,it} ) .call(this, ( (function(first,rest_fn) {return this.first=first,this.rest=rest_fn} ) ) ) ,k=function(x) {;
return function() {;
return x} } ,map=function(f,xs) {;
return xs.reduce(k(null) , (function(x,rest) {return cons(f(x) ,rest) } ) ) } ,append=function(xs,ys_f) {;
return xs===null?ys_f() 
:xs.reduce(ys_f,cons) } ,filter=function(f,xs) {;
return xs.reduce(k(null) , (function(x,rest) {return f(x) ?cons(x,rest) 
:rest() } ) ) } ,each=function(f,xs) {;
return xs.reduce(k(xs) , (function(x,rest) {return f(x) ,rest() } ) ) } ,take_while=function(f,xs) {;
return xs.reduce(k(null) , (function(x,rest) {return f(x) ?cons(x,rest) 
:null} ) ) } ,descend_while=function(f,xs) {;
return xs.reduce?xs.reduce(k(null) , (function(x,rest) {return take_while(f,append(descend_while(f,k(x) ) ,function(_) {return descend_while(f,rest() ) } ) ) } ) ) 
:x} ,bounded=function(s,box) {;
return{bound:function() {;
return box} ,reduce:function(x,f) {;
return f(s,x) } } } ,x_shadow=function(s,bound) {;
return bounded(s, (bound) .times( [1/0,1] ) ) } ,x_stack=function(xs) {;
return x_shadow(xs,xs.first.bound() ) } ,y_shadow=function(s,bound) {;
return bounded(s, (bound) .times( [1,1/0] ) ) } ,y_stack=function(xs) {;
return y_shadow(xs,xs.first.bound() ) } ,rectangle_path=function(b,c) {;
return c.rect(b.v[0] ,b.v[1] ,b.v[0] +b.dv[0] ,b.v[1] +b.dv[1] ) } ,arc_path=function(b,c) {;
return( ( ( ( (c.save() ,c.rotate(b.v[1] ) ) ,c.arc(0,0,b.v[0] ,0,b.dv[1] ) ) ,c.arc(0,0,b.v[0] +b.dv[0] ,b.dv[1] ,0,true) ) ,c.lineTo(b.v[0] ,0) ) ,c.restore() ) } ,arc_bound=function(b) {var p= (b) .transform_with(inverse_polar) ;
var cp1= (polar) .transform( [p.v[0] ,p.v[1] +p.dv[1] ] ) ;
var cp2= (polar) .transform( [p.v[0] +p.dv[0] ,p.v[1] ] ) ;
return(b) .union(box(cp1,cp2) ) } ,cosine_tween=function(x) {;
return Math.cos(x*Math.PI) * -0.5+0.5} ,viewport=function(data,zoom,view) {;
return{transformed_data:function() {;
return( (data) .transform_with(zoom) ) .transform_with(view) } ,with_zoom:function(z) {;
return viewport(data,z,view) } ,animate:function(to,duration,tween) {;
return animation(this,to,duration||400,tween||cosine_tween) } ,with_data:function(d) {;
return viewport(d,zoom,view) } ,find:function(v) {;
return descend_while(function(_) {return _.bound() .contains(v) } ) .first} ,zoom:function() {;
return zoom} ,view:function() {;
return view} ,data:function() {;
return data} ,interpolate:function(v,x) {;
return(this) .with_zoom(zoom.interpolate(v.zoom() ,x) ) } } } ,animation=function(v1,v2,duration,tween) {;
return{start: +new Date,viewport:function() {;
return v1.interpolate(v2,this.factor() ) } ,is_complete:function() {;
return+new Date-start>duration} ,factor:function() {var t= +new Date;
return Math.min(1,tween( (t-start) /duration) ) } } } ,drag_events=function(canvas) {;
return(function() {var last_x=0,last_y=0,dragging=false,last_selected=null,$doc=jQuery(document) ,self=jQuery(canvas) ,record=function(x,y) {;
return(last_x=x,last_y=y) } ,start_dragging=function(e) {;
return(record(e.pageX,e.pageY) , ( ($doc) .mousemove(drag) ) .mouseup(stop_dragging) ) } ,stop_dragging=function(e) {;
return $doc.unbind( 'mousemove' ,drag) .unbind( 'mouseup' ,stop_dragging) } ,drag=function(e) {;
return(self.trigger( 'drag_delta' ,$.merge( {} ,e, {dx:e.pageX-last_x,dy:e.pageY-last_y} ) ) ,record(e.pageX,e.pageY) ) } ;
return( !self.data( 'splunge_drag_delta_installed' ) &&self.mousedown(start_dragging) .data( 'splunge_drag_delta_installed' ,true) ,self) } ) .call(this) } ,default_interaction=function(canvas,v) {;
return(function() {var x_scale=function(v) {;
return v.transform() .dx} ,pan_or_scale=function(e) {;
return e.shiftKey?scale(e) 
:pan(e) } ,y_scale=function(v) {;
return v.transform() .dy} ,scale=function(e) {;
return v.transform(plus(base(v.transform() ) ,times(d(v.transform() ) , {x:e.dx,y:e.dy} ) ) ) } ;
return drag_events(canvas) .on( 'drag_delta' ,pan_or_scale) } ) .call(this) } } ) .call: (function() {var vplus=e1.vplus,vtimes=e1.vtimes,vminus=e1.vminus,vscale=e1.vscale,vdot=e1.vdot,vnorm=e1.vnorm,vmin=e1.vmin,vmax=e1.vmax,vmacv=e1.vmacv,vmacs=e1.vmacs,vunit=e1.vunit,vproj=e1.vproj,vorth=e1.vorth;
return atan_scale=2/Math.PI,scaled_atan=function(x) {;
return Math.atan(x) *atan_scale} ,clip=function(x) {;
return Math.min(Math.max(x, -1) ,1) } ,id=function(x) {;
return x} ,scaled_tan=function(x) {;
return Math.tan(clip(x/atan_scale) ) } ,componentwise=function(f1,f2) {;
return function(v) {;
return[f1(v[0] ) ,f2(v[1] ) ] } } ,x_tangent= {transform:componentwise(scaled_tan,id) ,inverse:function() {;
return x_arctangent} } ,x_arctangent= {transform:componentwise(scaled_atan,id) ,inverse:function() {;
return x_tangent} } ,y_tangent= {transform:componentwise(id,scaled_tan) ,inverse:function() {;
return y_arctangent} } ,y_arctangent= {transform:componentwise(id,scaled_atan) ,inverse:function() {;
return y_tangent} } ,inverse_polar= {transform:function(v) {var d=vnorm(v) ;
var t=Math.atan2(v[0] ,v[1] ) ;
return[d,t] } ,inverse:function() {;
return polar} } ,polar= {transform:function(v) {var d=v[0] ;
var t=v[1] ;
return[d*Math.cos(t) ,d*Math.sin(t) ] } ,inverse:function() {;
return inverse_polar} } ,composite=function() {var ts=arguments;
return{transform:function(v) {;
return(function(xs) {var x,x0,xi,xl,xr;
for(var x0= (v) ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,x0= (x(x0) ) ;
return x0} ) .call(this,ts) } ,inverse:function() {;
return composite.apply(this, (function(xs) {var x,x0,xi,xl,xr;
for(var xr=new xs.constructor() ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,xr.push( (ts[xl-xi-1] .inverse() ) ) ;
return xr} ) .call(this,ts) ) } } } ,box=function(v,dv) {;
return new box_ctor(v,dv) } ,translate=function(v) {;
return new box_ctor(v, [1,1] ) } ,bound_everything=box( [ -1/0, -1/0] , [1/0,1/0] ) ,rectangle=function(data,v,dv) {var b=box(v,dv) ;
return(b.data=data,b) } ,scale=function(v) {;
return new box_ctor( [0,0] ,v) } ,bound_nothing=box( [0,0] , [0,0] ) ,box_ctor= (function(it) {return $.merge(it.prototype, {area:function() {;
return this.dv[0] *this.dv[1] } ,plus:function(b) {;
return box(vplus(this.v,b.v) ,vplus(this.dv,b.dv) ) } ,interpolate:function(b,x) {;
return(this.scale(1-x) ) .plus(b.scale(x) ) } ,scale:function(x) {;
return box(vscale(this.v,x) ,vscale(this.dv,x) ) } ,transform:function(v) {;
return vplus(this.v,vtimes(v,this.dv) ) } ,inverse:function() {;
return box(vscale(this.v, -1) , [1/this.dv[0] ,1/this.dv[1] ] ) } ,times:function(v) {;
return box(this.v,vtimes(v,this.dv) ) } ,bound:function() {;
return this} ,intersect:function(b) {;
return(this) .map_corners(function(_) {return(b) .intern(_) } ) } ,union:function(b) {;
return(function() {var c1=vmin(this.v,b.v) ,c2=vmax(vplus(this.v,this.dv) ,vplus(b.v,b.dv) ) ;
return box(c1,vminus(c2,c1) ) } ) .call(this) } ,transform_with:function(t) {;
return(this) .map_corners(function(_) {return(t) .transform(_) } ) } ,intern:function(v) {;
return vmin(vmax(v,this.v) ,vplus(this.v,this.dv) ) } ,contains:function(v) {;
return v[0] >=this.v[0] &&v[1] >=this.v[1] &&v[0] <=this.v[0] +this.dv[0] &&v[1] <=this.v[1] +this.dv[1] } ,map_corners:function(f) {;
return(function() {var c1=f(this.v) ,c2=f(vplus(this.v,this.dv) ) ;
return rectangle(this.data,c1,vminus(c2,c1) ) } ) .call(this) } } ) ,it} ) .call(this, ( (function(v,dv) {return this.v=v,this.dv=dv} ) ) ) ,cons=function(first,rest_fn) {;
return new cons_ctor(first,rest_fn) } ,cons_from_array=function(xs) {;
return(function(xs) {var x,x0,xi,xl,xr;
for(var x0= (null) ,xi=0,xl=xs.length;
xi<xl;
 ++xi)x=xs[xi] ,x0= (cons(x,k(x0) ) ) ;
return x0} ) .call(this,xs) } ,cons_to_array=function(c) {;
return c.reduce( [] , (function(x,rest) {return[x] .concat(rest() ) } ) ) } ,cons_ctor= (function(it) {return $.merge(it.prototype, {reduce:function(x,f) {var r=this.rest;
return f(this.first,r?function(_) {return r.reduce(x,f) } 
:x) } ,transform_with:function(t) {;
return map(function(_) {return _.transform_with(t) } ,this) } ,bound:function() {;
return bound_everything} } ) ,it} ) .call(this, ( (function(first,rest_fn) {return this.first=first,this.rest=rest_fn} ) ) ) ,k=function(x) {;
return function() {;
return x} } ,map=function(f,xs) {;
return xs.reduce(k(null) , (function(x,rest) {return cons(f(x) ,rest) } ) ) } ,append=function(xs,ys_f) {;
return xs===null?ys_f() 
:xs.reduce(ys_f,cons) } ,filter=function(f,xs) {;
return xs.reduce(k(null) , (function(x,rest) {return f(x) ?cons(x,rest) 
:rest() } ) ) } ,each=function(f,xs) {;
return xs.reduce(k(xs) , (function(x,rest) {return f(x) ,rest() } ) ) } ,take_while=function(f,xs) {;
return xs.reduce(k(null) , (function(x,rest) {return f(x) ?cons(x,rest) 
:null} ) ) } ,descend_while=function(f,xs) {;
return xs.reduce?xs.reduce(k(null) , (function(x,rest) {return take_while(f,append(descend_while(f,k(x) ) ,function(_) {return descend_while(f,rest() ) } ) ) } ) ) 
:x} ,bounded=function(s,box) {;
return{bound:function() {;
return box} ,reduce:function(x,f) {;
return f(s,x) } } } ,x_shadow=function(s,bound) {;
return bounded(s, (bound) .times( [1/0,1] ) ) } ,x_stack=function(xs) {;
return x_shadow(xs,xs.first.bound() ) } ,y_shadow=function(s,bound) {;
return bounded(s, (bound) .times( [1,1/0] ) ) } ,y_stack=function(xs) {;
return y_shadow(xs,xs.first.bound() ) } ,rectangle_path=function(b,c) {;
return c.rect(b.v[0] ,b.v[1] ,b.v[0] +b.dv[0] ,b.v[1] +b.dv[1] ) } ,arc_path=function(b,c) {;
return( ( ( ( (c.save() ,c.rotate(b.v[1] ) ) ,c.arc(0,0,b.v[0] ,0,b.dv[1] ) ) ,c.arc(0,0,b.v[0] +b.dv[0] ,b.dv[1] ,0,true) ) ,c.lineTo(b.v[0] ,0) ) ,c.restore() ) } ,arc_bound=function(b) {var p= (b) .transform_with(inverse_polar) ;
var cp1= (polar) .transform( [p.v[0] ,p.v[1] +p.dv[1] ] ) ;
var cp2= (polar) .transform( [p.v[0] +p.dv[0] ,p.v[1] ] ) ;
return(b) .union(box(cp1,cp2) ) } ,cosine_tween=function(x) {;
return Math.cos(x*Math.PI) * -0.5+0.5} ,viewport=function(data,zoom,view) {;
return{transformed_data:function() {;
return( (data) .transform_with(zoom) ) .transform_with(view) } ,with_zoom:function(z) {;
return viewport(data,z,view) } ,animate:function(to,duration,tween) {;
return animation(this,to,duration||400,tween||cosine_tween) } ,with_data:function(d) {;
return viewport(d,zoom,view) } ,find:function(v) {;
return descend_while(function(_) {return _.bound() .contains(v) } ) .first} ,zoom:function() {;
return zoom} ,view:function() {;
return view} ,data:function() {;
return data} ,interpolate:function(v,x) {;
return(this) .with_zoom(zoom.interpolate(v.zoom() ,x) ) } } } ,animation=function(v1,v2,duration,tween) {;
return{start: +new Date,viewport:function() {;
return v1.interpolate(v2,this.factor() ) } ,is_complete:function() {;
return+new Date-start>duration} ,factor:function() {var t= +new Date;
return Math.min(1,tween( (t-start) /duration) ) } } } ,drag_events=function(canvas) {;
return(function() {var last_x=0,last_y=0,dragging=false,last_selected=null,$doc=jQuery(document) ,self=jQuery(canvas) ,record=function(x,y) {;
return(last_x=x,last_y=y) } ,start_dragging=function(e) {;
return(record(e.pageX,e.pageY) , ( ($doc) .mousemove(drag) ) .mouseup(stop_dragging) ) } ,stop_dragging=function(e) {;
return $doc.unbind( 'mousemove' ,drag) .unbind( 'mouseup' ,stop_dragging) } ,drag=function(e) {;
return(self.trigger( 'drag_delta' ,$.merge( {} ,e, {dx:e.pageX-last_x,dy:e.pageY-last_y} ) ) ,record(e.pageX,e.pageY) ) } ;
return( !self.data( 'splunge_drag_delta_installed' ) &&self.mousedown(start_dragging) .data( 'splunge_drag_delta_installed' ,true) ,self) } ) .call(this) } ,default_interaction=function(canvas,v) {;
return(function() {var x_scale=function(v) {;
return v.transform() .dx} ,pan_or_scale=function(e) {;
return e.shiftKey?scale(e) 
:pan(e) } ,y_scale=function(v) {;
return v.transform() .dy} ,scale=function(e) {;
return v.transform(plus(base(v.transform() ) ,times(d(v.transform() ) , {x:e.dx,y:e.dy} ) ) ) } ;
return drag_events(canvas) .on( 'drag_delta' ,pan_or_scale) } ) .call(this) } } ) .call} } ) .call(this) } ) ;
result.caterwaul_expression_ref_table= {e1: ( "caterwaul.vector(2, 'v' )" ) } ;
return(result) } ) .call(this,caterwaul.vector(2, 'v' ) ) ) ;
